name: about_page
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/profile1.jpg
    - assets/profile2.jpg
    - assets/profile3.jpg
    - assets/profile4.jpg
    - assets/profile5.jpg
